# Generated by Django 3.2.18 on 2023-05-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(choices=[('product', 'About a product'), ('services', 'About our services'), ('order', 'About an order'), ('delivery', 'About delivery'), ('enquiry', 'General enquiry'), ('Claim or Complain', 'Claim or Complain')], max_length=30),
        ),
    ]
