# Generated by Django 3.2.18 on 2023-04-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='incomming',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
