# Generated by Django 3.2.18 on 2023-04-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sts_store', '0002_ware_incomming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wareimage',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ware_image', to='sts_store.ware'),
        ),
    ]
